apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-pv
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: abc.azurecr.io/my-app:pv-2024-10-22_211426
        ports:
        - containerPort: 5009
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: acr-docker-registry
